services:
  traefik:
    image: traefik:v2.11
    container_name: traefik_proxy
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      # (Optional) Đảm bảo dashboard được bật
      - --api.dashboard=true
    ports:
      - "80:80"
      - "8088:8080" # dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web_gateway

  networks:
  web_gateway:
    external: true